language: go
go:
- 1.13.x
addons:
  apt:
    packages:
    - python3
script:
- python3 ./build.py -create-sample
before_deploy:
- go version
- ls -al
- python3 ./build.py -build
deploy:
  provider: releases
  api_key:
    secure: jpgW48ebSxAWpybEWm8JqfQUf672ADCEwWHe5kG3AufCV1tPtZ1IdfRezai3cHEPdWrQIH6Qvg+63DlFuKCogga1dz3Ms89vQ+ElgzcfM28d9crbN8+dWq1X7zXENznFF5s01s58KKMK0qFxj7tpYKftq6iZBqSwglW6N7slbt6nyB/+9rrQBVEXGPtwTzY1t7kKaK3HGUjEtbWcjyqDgq9ZsMVYrWqo+Dcwa5VrUpA4K25uBj3wIm8rCHn651cRQXpo8bsZpR7Nm4IE62i4PwXJ6wkHnmvLlkZVwyECDNUOtUFMJKYpeNjPS/oWukBJTbtQ6u7852AgjBRW720jTjXHpnZ7f6XaBgjOqJgdCuJMjERdjF+2FPLrO1RZ0DtdRDEK/QqGbktx1uKcSi90P5ef/uZthNhwCuLk6Nwmkqi5yQCio+vLC5iYsPa2YDO8NXkk0QNWerz+B4J40FERmkIez/Du+w/SELZCNRvFx7ZRoN95EFF4+B5hoj+PGJyZiiBfkMDDgn1pQPXouXXy7YbURPudQ+7uFZbAHwpaW2+Tpp8P1nuCtrA0wkcHA9WW/WXEKsdG0A0XgKScyNDl9VIz3Yky6yTmljrLnsI5iDmnghE5hlbGErC/iJUCLhwYfm8jUhealX1HMFuoXq3kd9SOnbGiSuw7kFQNqVJNvBo=
  file:
    - BGPParser-linux-386.zip
    - BGPParser-linux-amd64.zip
    - BGPParser-linux-arm.zip
    - BGPParser-linux-arm64.zip
    - BGPParser-linux-mips-softfloat.zip
    - BGPParser-linux-mips-hardfloat.zip
    - BGPParser-linux-mipsle-softfloat.zip
    - BGPParser-linux-mipsle-hardfloat.zip
    - BGPParser-linux-mips64.zip
    - BGPParser-linux-mips64le.zip
    - BGPParser-freebsd-386.zip
    - BGPParser-freebsd-amd64.zip
    - BGPParser-windows-386.zip
    - BGPParser-windows-amd64.zip
  skip_cleanup: true      
  on:
    tags: yes
